### ISSUE TITLE
Practica de Reconocimiento de Imágenes

### ISSUE THREAD

**Issue by Itzelzun** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipofrancisco#2]
[Practica de Reconocimiento de Imagenes.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipofrancisco/files/6454360/Practica.de.Reconocimiento.de.Imagenes.pdf)

**Comment by AxayacatlS** [comment]
Calificación: 20
Excelente trabajo ;)

**Comment by josealfredo79** [comment]
En esta practica no explican el procedimiento de las actividades...solamente...ponen el pie de la foto...

**Comment by josealfredo79** [comment]
Para la proxima si no describen la practica no se puede tomar en cuenta.
